kind: pipeline
type: docker
name: default
platform:
  os: linux
  arch: arm64
steps:
- name: docker  
  image: plugins/docker
  settings:
    dockerfile: ./php/7.4/Dockerfile
    context: .
    registry: docker.io
    mirror: mirror.gcr.io
    username:
      from_secret: DOCKER_HUB_USER
    password:
      from_secret: DOCKER_HUB_SECRET
    email:
      from_secret: DOCKER_HUB_EMAIL
