#!/usr/bin/env sh

set -e

until nc -z -v -w30 $DATABASE_HOST $DATABASE_PORT
do
  echo "Waiting for database connection..."
  # wait for 5 seconds before check again
  sleep 5
done

update_all_plugins() {
  list_with_updates=$(php bin/console plugin:list --json | jq 'map(select(.value.upgradeVersion != null)) | .[].name' -r)

  for plugin in $list_with_updates; do
    php bin/console plugin:update $plugin
  done
}

install_all_plugins() {
  list_with_updates=$(php bin/console plugin:list --json | jq 'map(select(.value.installedAt == null)) | .[].name' -r)

  for plugin in $list_with_updates; do
    php bin/console plugin:install --activate $plugin
  done
}

if php bin/console system:config:get shopware.installed; then
  php bin/console system:update:finish
  php bin/console plugin:refresh

  update_all_plugins
  install_all_plugins
  php bin/console theme:compile
else
  # Shopware is not installed
  php bin/console system:install --create-database "--shop-locale=$INSTALL_LOCALE" "--shop-currency=$INSTALL_CURRENCY" --force
  php bin/console user:create "$INSTALL_ADMIN_USERNAME" --admin --password="$INSTALL_ADMIN_PASSWORD" -n
  php bin/console sales-channel:create:storefront --name=Storefront --url="$APP_URL"
  php bin/console theme:change --all Storefront
  php bin/console plugin:refresh

  install_all_plugins
fi
