framework:
    cache:
        app: cache.adapter.redis
        system: cache.adapter.redis
        pools:
            cache.serializer:
                adapter: cache.adapter.redis
            cache.annotations:
                adapter: cache.adapter.redis
            cache.property_info:
                adapter: cache.adapter.redis
            cache.messenger:
                adapter: cache.adapter.redis
            cache.property_access:
                adapter: cache.adapter.redis
        default_redis_provider: "redis://%env(REDIS_CACHE_HOST)%:%env(REDIS_CACHE_PORT)%/%env(REDIS_CACHE_DATABASE)%"
